[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program = "EN3hAGsNiDrR8rnNriVaMc2sYPzZQjiRugeXESy4CKMz"

[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
